"""add catalyst_events table

Revision ID: a84e6b57a109
Revises: c15d6e76ea0f
Create Date: 2026-06-04 21:49:18.864715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84e6b57a109'
down_revision: Union[str, Sequence[str], None] = 'c15d6e76ea0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalyst_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_hour', sa.String(length=8), nullable=True),
    sa.Column('estimated_eps', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estimated_revenue_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'event_type', 'event_date', name='uq_catalyst_symbol_type_date')
    )
    op.create_index(op.f('ix_catalyst_events_event_date'), 'catalyst_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_catalyst_events_event_type'), 'catalyst_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_catalyst_events_state'), 'catalyst_events', ['state'], unique=False)
    op.create_index(op.f('ix_catalyst_events_symbol'), 'catalyst_events', ['symbol'], unique=False)
    op.create_index(op.f('ix_catalyst_events_thesis_id'), 'catalyst_events', ['thesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalyst_events_thesis_id'), table_name='catalyst_events')
    op.drop_index(op.f('ix_catalyst_events_symbol'), table_name='catalyst_events')
    op.drop_index(op.f('ix_catalyst_events_state'), table_name='catalyst_events')
    op.drop_index(op.f('ix_catalyst_events_event_type'), table_name='catalyst_events')
    op.drop_index(op.f('ix_catalyst_events_event_date'), table_name='catalyst_events')
    op.drop_table('catalyst_events')
    # ### end Alembic commands ###
