"""add triage_decisions table

Revision ID: b507243bb597
Revises: a84e6b57a109
Create Date: 2026-06-08 16:54:16.655276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b507243bb597'
down_revision: Union[str, Sequence[str], None] = 'a84e6b57a109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('body_excerpt', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_triage_decided', 'triage_decisions', ['decided_at'], unique=False)
    op.create_index('idx_triage_symbol_decided', 'triage_decisions', ['symbol', 'decided_at'], unique=False)
    op.create_index(op.f('ix_triage_decisions_decided_at'), 'triage_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_triage_decisions_event_id'), 'triage_decisions', ['event_id'], unique=True)
    op.create_index(op.f('ix_triage_decisions_passed'), 'triage_decisions', ['passed'], unique=False)
    op.create_index(op.f('ix_triage_decisions_source'), 'triage_decisions', ['source'], unique=False)
    op.create_index(op.f('ix_triage_decisions_symbol'), 'triage_decisions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_decisions_symbol'), table_name='triage_decisions')
    op.drop_index(op.f('ix_triage_decisions_source'), table_name='triage_decisions')
    op.drop_index(op.f('ix_triage_decisions_passed'), table_name='triage_decisions')
    op.drop_index(op.f('ix_triage_decisions_event_id'), table_name='triage_decisions')
    op.drop_index(op.f('ix_triage_decisions_decided_at'), table_name='triage_decisions')
    op.drop_index('idx_triage_symbol_decided', table_name='triage_decisions')
    op.drop_index('idx_triage_decided', table_name='triage_decisions')
    op.drop_table('triage_decisions')
    # ### end Alembic commands ###
