"""initial: theses + thesis_outcomes

Revision ID: bafb81fa8ab8
Revises: 
Create Date: 2026-06-01 09:27:02.846647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafb81fa8ab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=False),
    sa.Column('source_bucket', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prediction_window_days', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('suggested_contract', sa.JSON(), nullable=True),
    sa.Column('grounding_check_passed', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=False),
    sa.Column('funnel_latency_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_theses_bucket_generated', 'theses', ['source_bucket', 'generated_at'], unique=False)
    op.create_index(op.f('ix_theses_correlation_id'), 'theses', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_theses_generated_at'), 'theses', ['generated_at'], unique=False)
    op.create_index(op.f('ix_theses_source_bucket'), 'theses', ['source_bucket'], unique=False)
    op.create_index(op.f('ix_theses_symbol'), 'theses', ['symbol'], unique=False)
    op.create_table('thesis_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('realized_direction', sa.String(length=8), nullable=False),
    sa.Column('hit', sa.Boolean(), nullable=False),
    sa.Column('underlying_price_at_thesis', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('underlying_price_at_eval', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('pct_move', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_outcomes_thesis_id'), 'thesis_outcomes', ['thesis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_outcomes_thesis_id'), table_name='thesis_outcomes')
    op.drop_table('thesis_outcomes')
    op.drop_index(op.f('ix_theses_symbol'), table_name='theses')
    op.drop_index(op.f('ix_theses_source_bucket'), table_name='theses')
    op.drop_index(op.f('ix_theses_generated_at'), table_name='theses')
    op.drop_index(op.f('ix_theses_correlation_id'), table_name='theses')
    op.drop_index('idx_theses_bucket_generated', table_name='theses')
    op.drop_table('theses')
    # ### end Alembic commands ###
