"""add position_marks table and shadow_trades close columns

Revision ID: c15d6e76ea0f
Revises: 68b247b4a5dd
Create Date: 2026-06-04 16:45:09.495612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15d6e76ea0f'
down_revision: Union[str, Sequence[str], None] = '68b247b4a5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_marks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shadow_trade_id', sa.Integer(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying_price_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('option_mid_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mark_price_per_contract_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unrealized_pnl_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['shadow_trade_id'], ['shadow_trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_position_marks_trade_marked', 'position_marks', ['shadow_trade_id', 'marked_at'], unique=False)
    op.create_index(op.f('ix_position_marks_marked_at'), 'position_marks', ['marked_at'], unique=False)
    op.create_index(op.f('ix_position_marks_shadow_trade_id'), 'position_marks', ['shadow_trade_id'], unique=False)
    op.add_column('shadow_trades', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shadow_trades', sa.Column('close_reason', sa.String(length=32), nullable=True))
    op.add_column('shadow_trades', sa.Column('close_price_per_contract_usd', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('shadow_trades', sa.Column('realized_pnl_usd', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shadow_trades', 'realized_pnl_usd')
    op.drop_column('shadow_trades', 'close_price_per_contract_usd')
    op.drop_column('shadow_trades', 'close_reason')
    op.drop_column('shadow_trades', 'closed_at')
    op.drop_index(op.f('ix_position_marks_shadow_trade_id'), table_name='position_marks')
    op.drop_index(op.f('ix_position_marks_marked_at'), table_name='position_marks')
    op.drop_index('idx_position_marks_trade_marked', table_name='position_marks')
    op.drop_table('position_marks')
    # ### end Alembic commands ###
