"""add portfolio tables

Revision ID: fee6c336e464
Revises: bafb81fa8ab8
Create Date: 2026-06-03 23:02:15.792641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee6c336e464'
down_revision: Union[str, Sequence[str], None] = 'bafb81fa8ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('starting_balance_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('max_trade_cost_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_accounts_kind'), 'paper_accounts', ['kind'], unique=True)
    op.create_table('shadow_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=False),
    sa.Column('occ_symbol', sa.String(length=32), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('premium_per_contract_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shadow_trades_account_opened', 'shadow_trades', ['account_id', 'opened_at'], unique=False)
    op.create_index(op.f('ix_shadow_trades_account_id'), 'shadow_trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_shadow_trades_expiration'), 'shadow_trades', ['expiration'], unique=False)
    op.create_index(op.f('ix_shadow_trades_opened_at'), 'shadow_trades', ['opened_at'], unique=False)
    op.create_index(op.f('ix_shadow_trades_thesis_id'), 'shadow_trades', ['thesis_id'], unique=False)
    op.create_index(op.f('ix_shadow_trades_underlying'), 'shadow_trades', ['underlying'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_trades_underlying'), table_name='shadow_trades')
    op.drop_index(op.f('ix_shadow_trades_thesis_id'), table_name='shadow_trades')
    op.drop_index(op.f('ix_shadow_trades_opened_at'), table_name='shadow_trades')
    op.drop_index(op.f('ix_shadow_trades_expiration'), table_name='shadow_trades')
    op.drop_index(op.f('ix_shadow_trades_account_id'), table_name='shadow_trades')
    op.drop_index('idx_shadow_trades_account_opened', table_name='shadow_trades')
    op.drop_table('shadow_trades')
    op.drop_index(op.f('ix_paper_accounts_kind'), table_name='paper_accounts')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
